LGraph CreateGraph(int Nodenum);
void InsertEdge(LGraph Graph, Edge E);
void load(ids s);
void oldnew(newn n);
int findid(newn n,int oldid);
int returnid(newn n,int newid);
double get_lon(newn n,int id);
double get_lat(newn n,int id);
int exist_id(newn n,int id);
LGraph BuildGraph(newn n);
